vm_virtio_net: Test scripts print success output
Updated the arping and ping test scripts to print a success or
failure print based on the result of the test.

diff --git a/apps/vm_virtio_net/overlay_files/init_scripts/arping_test b/apps/vm_virtio_net/overlay_files/init_scripts/arping_test
--- a/apps/vm_virtio_net/overlay_files/init_scripts/arping_test
+++ b/apps/vm_virtio_net/overlay_files/init_scripts/arping_test
@@ -11,7 +11,12 @@
 # @TAG(DATA61_BSD)
 #
 
-set -e
-
 echo "Testing arping on virtual interface:"
-arping 192.168.1.2 -c 5
+arping 192.168.1.2 -c 5 -w 2
+# Success code for arping: 0 (arping returns non-zero value if packet count and timeout is not met)
+if [ $? -eq 0 ]
+then
+    echo "arping test was successful"
+else
+    echo "arping test failed"
+fi
diff --git a/apps/vm_virtio_net/overlay_files/init_scripts/ping_test b/apps/vm_virtio_net/overlay_files/init_scripts/ping_test
--- a/apps/vm_virtio_net/overlay_files/init_scripts/ping_test
+++ b/apps/vm_virtio_net/overlay_files/init_scripts/ping_test
@@ -11,7 +11,12 @@
 # @TAG(DATA61_BSD)
 #
 
-set -e
-
 echo "Testing ping on virtual interface:"
-ping 192.168.1.2 -v -c 5
+ping 192.168.1.2 -v -c 5 -W 2
+# Success code for Ping: 0 (Ping returns non-zero value if packet count and timeout is not met)
+if [ $? -eq 0 ]
+then
+    echo "Ping test was successful"
+else
+    echo "Ping test failed"
+fi
